version: '3.8'
services:
  db:
    image: mysql:8.4
    container_name: mysql-node-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gantt_db
      MYSQL_USER: hiro
      MYSQL_PASSWORD: hiro_password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_test_data:/var/lib/mysql
