-- AlterTable
ALTER TABLE `GanttChart` MODIFY `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `createdBy` VARCHAR(191) NULL DEFAULT 'system',
    MODIFY `updatedBy` VARCHAR(191) NULL DEFAULT 'system';

-- AlterTable
ALTER TABLE `GanttRow` MODIFY `createdBy` VARCHAR(191) NULL DEFAULT 'system',
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedBy` VARCHAR(191) NULL DEFAULT 'system',
    MODIFY `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `GanttTask` MODIFY `createdBy` VARCHAR(191) NULL DEFAULT 'system',
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedBy` VARCHAR(191) NULL DEFAULT 'system',
    MODIFY `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
