/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/common/AlertDialog.vue')['default']
    ChartContextMenu: typeof import('./src/components/ChartContextMenu.vue')['default']
    CollaborationActivityLog: typeof import('./src/components/CollaborationActivityLog.vue')['default']
    ColorInput: typeof import('./src/components/common/ColorInput.vue')['default']
    ColorPaletteInput: typeof import('./src/components/common/ColorPaletteInput.vue')['default']
    ColorPaletteSelect: typeof import('./src/components/common/ColorPaletteSelect.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DialogProvider: typeof import('./src/components/common/DialogProvider.vue')['default']
    GoogleIcon: typeof import('./src/components/icons/GoogleIcon.vue')['default']
    HelpText: typeof import('./src/components/common/HelpText.vue')['default']
    LabelFilter: typeof import('./src/components/LabelFilter.vue')['default']
    LabelInput: typeof import('./src/components/common/LabelInput.vue')['default']
    LabelSelect: typeof import('./src/components/LabelSelect.vue')['default']
    LoginPrompt: typeof import('./src/components/LoginPrompt.vue')['default']
    OperationManualDrawer: typeof import('./src/components/OperationManualDrawer.vue')['default']
    ProjectDetailDialog: typeof import('./src/components/ProjectDetailDialog.vue')['default']
    ProjectListDialog: typeof import('./src/components/ProjectListDialog.vue')['default']
    PromptDialog: typeof import('./src/components/common/PromptDialog.vue')['default']
    RoleChip: typeof import('./src/components/RoleChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowEditDialog: typeof import('./src/components/RowEditDialog.vue')['default']
    RowHeaderContextMenu: typeof import('./src/components/RowHeaderContextMenu.vue')['default']
    Snackbar: typeof import('./src/components/common/Snackbar.vue')['default']
    SnapshotListDialog: typeof import('./src/components/SnapshotListDialog.vue')['default']
    TaskCommentDialog: typeof import('./src/components/TaskCommentDialog.vue')['default']
    TaskContextMenu: typeof import('./src/components/TaskContextMenu.vue')['default']
    TaskDetailDialog: typeof import('./src/components/TaskDetailDialog.vue')['default']
    TaskFormDialog: typeof import('./src/components/TaskFormDialog.vue')['default']
    TaskTemplateDialog: typeof import('./src/components/TaskTemplateDialog.vue')['default']
    TemplateContextMenu: typeof import('./src/components/TemplateContextMenu.vue')['default']
    TooltipBtn: typeof import('./src/components/common/TooltipBtn.vue')['default']
    TutorialOverlay: typeof import('./src/components/common/TutorialOverlay.vue')['default']
    UnassignedTaskSidebar: typeof import('./src/components/UnassignedTaskSidebar.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    UserDetailDialog: typeof import('./src/components/UserDetailDialog.vue')['default']
    UsersInput: typeof import('./src/components/common/UsersInput.vue')['default']
    ZoomControls: typeof import('./src/components/ZoomControls.vue')['default']
  }
}
