/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/AlertDialog.vue')['default']
    ColorInput: typeof import('./src/components/common/ColorInput.vue')['default']
    ColorPaletteInput: typeof import('./src/components/common/ColorPaletteInput.vue')['default']
    ColorPaletteSelect: typeof import('./src/components/common/ColorPaletteSelect.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DialogProvider: typeof import('./src/components/DialogProvider.vue')['default']
    GoogleIcon: typeof import('./src/components/icons/GoogleIcon.vue')['default']
    LoginPrompt: typeof import('./src/components/LoginPrompt.vue')['default']
    ProjectDetailDialog: typeof import('./src/components/ProjectDetailDialog.vue')['default']
    ProjectListDialog: typeof import('./src/components/ProjectListDialog.vue')['default']
    RoleChip: typeof import('./src/components/RoleChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowAddDialog: typeof import('./src/components/RowAddDialog.vue')['default']
    RowHeaderContextMenu: typeof import('./src/components/RowHeaderContextMenu.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    TaskContextMenu: typeof import('./src/components/TaskContextMenu.vue')['default']
    TaskDetailDialog: typeof import('./src/components/TaskDetailDialog.vue')['default']
    UserDetailDialog: typeof import('./src/components/UserDetailDialog.vue')['default']
  }
}
