-- AlterTable
ALTER TABLE `GanttRow`
    MODIFY `createdAt` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '作成日時',
    MODIFY `updatedAt` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新日時';

-- AlterTable
ALTER TABLE `GanttTask`
    MODIFY `createdAt` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '作成日時',
    MODIFY `updatedAt` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新日時';
